param()

$ErrorActionPreference = "Stop"

$repoRoot = (git rev-parse --show-toplevel).Trim()
if (-not $repoRoot) {
  throw "Cannot resolve git repository root."
}

$hooksDir = Join-Path $repoRoot ".git\hooks"
if (-not (Test-Path $hooksDir)) {
  New-Item -Path $hooksDir -ItemType Directory | Out-Null
}

$hookPath = Join-Path $hooksDir "post-commit"
$hookContent = @'
#!/usr/bin/env sh
# Auto-generated by scripts/install_git_hooks.ps1

if command -v python >/dev/null 2>&1; then
  python scripts/update_ai_changelog.py --from-latest-commit
elif command -v py >/dev/null 2>&1; then
  py -3 scripts/update_ai_changelog.py --from-latest-commit
else
  echo "[WARN] python not found; skip AI changelog auto update." >&2
fi
'@

Set-Content -Path $hookPath -Value $hookContent -Encoding UTF8

try {
  git update-index --chmod=+x .git/hooks/post-commit 2>$null | Out-Null
} catch {
  # Ignore on Windows if executable bit update fails.
}

Write-Output "[OK] post-commit hook installed/updated: $hookPath"
Write-Output "[TIP] Manual command: python scripts/update_ai_changelog.py --title 'Your Title'"

